# Version information used on all builds
PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID=MRA58K BUILD_ID=MRA58K BUILD_VERSION_TAGS=release-keys BUILD_UTC_DATE=0

# Versioning System
PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_MAINTENANCE = Beta-0.1

ifndef EOS_BUILD_TYPE
    EOS_BUILD_TYPE := UNOFFICIAL
    PLATFORM_VERSION_CODENAME := UNOFFICIAL
    EOS_POSTFIX := -$(shell date +"%Y%m%d-%H%M")
endif

# Set all versions
ROM_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(EOS_BUILD)-$(EOS_BUILD_TYPE)-$(shell date -u +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
  BUILD_DISPLAY_ID=$(BUILD_ID) \
  ro.eos.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
  eos.ota.version=$(shell date -u +%Y%m%d) \
  ro.modversion=$(ROM_VERSION)
